Submodules/GMaps.Mvc/GMaps.Mvc.Examples/Controllers/Basic/AjaxPartialViewController.cs
namespace GMaps.Mvc.Examples.Controllers
{
    using System.Web.Mvc;

    public partial class BasicController
    {
        // GET: AjaxPartialView
        public ActionResult AjaxPartialView()
        {
            return this.View();
        }

        public ActionResult GooglemapPartialView(string payload)
        {
            object model = payload;
            return this.PartialView("_GooglemapPartialView", model);
        }
    }
}

Submodules/GMaps.Mvc/GMaps.Mvc.Examples/Controllers/Basic/ClientEventsController.cs
namespace GMaps.Mvc.Examples.Controllers
{
    using System.Web.Mvc;

    public partial class BasicController
    {
        public ActionResult ClientEvents()
        {
            return this.View();
        }
    }
}

Submodules/GMaps.Mvc/GMaps.Mvc.Examples/Controllers/Basic/FirstLookController.cs
namespace GMaps.Mvc.Examples.Controllers
{
    using System.Web.Mvc;

    public partial class BasicController
    {
        public ActionResult FirstLook(int? height, int? width)
        {
            this.ViewData["height"] = height ?? 0;
            this.ViewData["width"] = width ?? 0;
            return this.View();
        }
    }
}

Submodules/GMaps.Mvc/GMaps.Mvc.Examples/Controllers/Basic/LanguageController.cs
namespace GMaps.Mvc.Examples.Controllers
{
    using System.Web.Mvc;

    public partial class BasicController
    {
        public ActionResult Language(string mapLanguage)
        {
            return this.View((object)(mapLanguage ?? "ru"));
        }
    }
}

Submodules/GMaps.Mvc/GMaps.Mvc.Examples/Controllers/Basic/MultiMapController.cs
namespace GMaps.Mvc.Examples.Controllers
{
    using System.Web.Mvc;

    public partial class BasicController
    {
        public ActionResult Multimap()
        {
            return this.View();
        }
    }
}

Submodules/GMaps.Mvc/GMaps.Mvc.Examples/Controllers/Basic/UIControlsController.cs
namespace GMaps.Mvc.Examples.Controllers
{
    using System.Web.Mvc;

    public partial class BasicController
    {
        public ActionResult UIControls(UIControlViewModel model)
        {
            return this.View(model);
        }
    }

    [System.Diagnostics.CodeAnalysis.SuppressMessage("StyleCop.CSharp.MaintainabilityRules", "SA1402:File may only contain a single class", Justification = "This allows to see the model type in the sample view")]
    public class UIControlViewModel
    {
        public UIControlViewModel()
        {
            this.ShowScaleControl = true;

            this.ShowPanControl = true;
            this.PanControlPosition = ControlPosition.TopLeft;

            this.ShowZoomControl = true;
            this.ZoomControlPosition = ControlPosition.TopLeft;
            this.ZoomControlStyle = ZoomControlStyle.Default;
            this.ScrollWheel = true;

            this.ShowStreetViewControl = true;
            this.StreetViewControlPosition = ControlPosition.TopLeft;

            this.ShowOverviewMapControl = true;
            this.OverviewMapControlOpened = true;

            this.ShowMapType = true;
            this.MapTypeControl = MapType.Roadmap;
            this.MapTypeControlStyle = MapTypeControlStyle.Default;
            this.MapTypeControlPosition = ControlPosition.TopRight;
        }

        public bool ShowScaleControl { get; set; }

        public bool ShowPanControl { get; set; }

        public ControlPosition PanControlPosition { get; set; }

        public bool ShowMapType { get; set; }

        public MapType MapTypeControl { get; set; }

        public MapTypeControlStyle MapTypeControlStyle { get; set; }

        public ControlPosition MapTypeControlPosition { get; set; }

        public bool ShowZoomControl { get; set; }

        public ControlPosition ZoomControlPosition { get; set; }

        public ZoomControlStyle ZoomControlStyle { get; set; }

        public bool ShowStreetViewControl { get; set; }

        public ControlPosition StreetViewControlPosition { get; set; }

        public bool OverviewMapControlOpened { get; set; }

        public bool ShowOverviewMapControl { get; set; }

        public bool ScrollWheel { get; set; }
    }
}

Submodules/GMaps.Mvc/GMaps.Mvc.Examples/Controllers/Basic/VersionController.cs
namespace GMaps.Mvc.Examples.Controllers
{
    using System.Web.Mvc;

    public partial class BasicController
    {
        public ActionResult Version(string version)
        {
            this.ViewData["version"] = version;
            return this.View();
        }
    }
}

Submodules/GMaps.Mvc/GMaps.Mvc.Examples/Controllers/BasicController.cs
namespace GMaps.Mvc.Examples.Controllers
{
    using System.Web.Mvc;

    public partial class BasicController : Controller
    {
        /* left only because of the attributes, which are example-agnostic */
    }
}

Submodules/GMaps.Mvc/GMaps.Mvc.Examples/Controllers/Marker/ClientEventsController.cs
namespace GMaps.Mvc.Examples.Controllers
{
    using System.Web.Mvc;

    public partial class MarkerController
    {
        public ActionResult ClientEvents(bool? clickable, bool? draggable)
        {
            this.ViewData["clickable"] = clickable ?? true;
            this.ViewData["draggable"] = draggable ?? true;
            return this.View();
        }
    }
}

Submodules/GMaps.Mvc/GMaps.Mvc.Examples/Views/Basic/AjaxPartialView.cshtml
@model dynamic

@{
    ViewBag.Title = "PartialView with Ajax";
}

<div style="height: 500px; border: solid 1px #cccccc" id="mapContainer">

</div>

<br />

<form class="form-horizontal" role="form">
    <h4> Google Map Settings</h4>

    <div class="form-group">
        <div class="col-sm-offset-1 col-sm-10">
            <button type="button" id="myButton" class="btn btn-default">Load Googlemap Partial View with Ajax</button>
        </div>
    </div>
</form>

@section scripts
{
    @(Html.GoogleMap().LoadScripts())

    <script type='text/javascript'>

        $('#myButton').click(function(e) {
            e.preventDefault();
            e.stopPropagation();

            new $.jmelosegui.GoogleMap('#mapContainer').ajax({
                url: '@Url.Action("GooglemapPartialView", "Basic")',
                type: "Get",
                data: { payload: 'from ajax call'},
                success: function(data) {
                    //alert('succeded');
                }
            });
        });

    </script>
}

Submodules/GMaps.Mvc/GMaps.Mvc.Examples/Views/Basic/ClientEvents.cshtml
@using GMaps.Mvc
@{
    ViewBag.Title = "Client Events";
    Layout = "~/Views/Shared/_LayoutExamples.cshtml";
}
<style>
    .event {
        transition: background-color 0.5s ease-out;
        padding-bottom: 2px;
    }

    .event.active {
        background-color: #99CCFF;
    }

     .event.inactive {
        background-color: transparent;
    }
</style>



<div id="main" class="row">
    <div class="col-md-10">
        @(Html.GoogleMap()
            .Name("map")
            .Height(420)
            .ClientEvents(events => events
                .OnMapBoundChanged("highlightEvent")
                .OnMapCenterChanged("highlightEvent")
                .OnMapClick("highlightEvent")
                .OnMapDoubleClick("highlightEvent")
                .OnMapRightClick("highlightEvent")
                .OnMapDrag("highlightEvent")
                .OnMapDragEnd("highlightEvent")
                .OnMapDragStart("highlightEvent")
                .OnMapHeadingChanged("highlightEvent")
                .OnMapIdle("highlightEvent")
                .OnMapTypeIdChanged("highlightEvent")
                .OnMouseMove("highlightEvent")
                .OnMouseOut("highlightEvent")
                .OnMouseOver("highlightEvent")
                .OnMapProjectionChanged("highlightEvent")
                .OnResize("highlightEvent")
                .OnTilesLoaded("highlightEvent")
                .OnTiltChanged("highlightEvent")
                .OnZoomChanged("highlightEvent")
                .OnMapLoaded("mapLoadedHandler")
            ))
    </div>
    <div id="events" class="col-md-2">
    </div>
</div>

@section Scripts{

    <script type="text/javascript">

        $(document).ready(function() {

            var events = [
                'bounds_changed', 'center_changed', 'click',
                'dblclick', 'drag', 'dragend',
                'dragstart', 'heading_changed', 'idle',
                'maptypeid_changed', 'mousemove', 'mouseout',
                'mouseover', 'projection_changed', 'resize',
                'rightclick', 'tilesloaded', 'tilt_changed',
                'zoom_changed'
            ];

            // Dynamically create the table of events from the defined hashmap
            function populateTable() {
                var eventsTable = document.getElementById('events');
                var content = '';
                for (var i = 0; i < events.length; i++) {
                    content += '<div class="event" id="' + events[i] + '">' + events[i] + '</div>';
                }
                eventsTable.innerHTML = content;
            }

            populateTable();
        });


        function highlightEvent(args) {
            var timeout;
            var eventRow = document.getElementById(args.eventName);
            eventRow.className = 'event active';
            clearTimeout(timeout);
            setTimeout(function() {
                eventRow.className = 'event inactive';
            }, 1000);
            if (args.eventName === 'click') {
                placeMarker(args.latLng, args.map);
            }
        }

        function placeMarker(position, map) {
            new google.maps.Marker({
                position: position,
                map: map
            });
            map.panTo(position);
        }

        function mapLoadedHandler(args) {
            var map = args.map;
            var position = map.getCenter();

            var options = {
                map: map,
                position: position,
                content: "Infowindow created on map loaded"
            };

            new google.maps.InfoWindow(options);
        }

    </script>
}

Submodules/GMaps.Mvc/GMaps.Mvc.Examples/Views/Basic/FirstLook.cshtml
@using GMaps.Mvc
@model dynamic

@{
    ViewBag.Title = "First Look";
}

<div style="height: 500px; border: solid 1px #cccccc">
    @(Html.GoogleMap()
          .Name("map")
          .Width((int)ViewData["width"])
          .Height((int)ViewData["height"]))
</div>

<br />

<form class="form-horizontal" role="form">
    <h4> Google Map Settings</h4>    
    <div class="form-group">
        <label for="width" class="col-sm-2 control-label">Width (px)</label>
        <div class="col-sm-4">
            @Html.TextBox("width", null, new { @class = "form-control", id = "mapHeight", placeholder = "Enter an integer value", @type = "number" })
            <label>0 for automatic with</label>
        </div>
        <label for="height" class="col-sm-2 control-label">Height (px)</label>
        <div class="col-sm-4">
            @Html.TextBox("height", null, new { @class = "form-control", id = "mapHeight", placeholder = "Enter an integer value", @type = "number" })
            <label>0 for automatic height</label>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-1 col-sm-10">
            <button type="submit" class="btn btn-default">Apply</button>
        </div>
    </div>
</form>

Submodules/GMaps.Mvc/GMaps.Mvc.Examples/Views/Basic/Language.cshtml
@using System.Globalization
@using GMaps.Mvc
@model String

@{
    ViewBag.Title = "Language";
}


@(Html.GoogleMap()
            .Name("map")
            .Height(300)
            .Culture(CultureInfo.GetCultureInfo(Model))
)

<br />

<form class="form-horizontal" role="form">
    <h4> Google Map Settings</h4>
    <div class="form-group">
        <label for="mapLanguage" class="col-sm-2 control-label" style="white-space: nowrap;">Map Language</label>
        <div class="col-sm-5">
            @Html.DropDownList("mapLanguage", 
                                CultureInfo.GetCultures(CultureTypes.NeutralCultures)
                                            .Select(ci => new SelectListItem
                                             {
                                                 Text = ci.EnglishName,
                                                 Value = ci.Name,
                                                 Selected = ci.EnglishName.Contains("Russian")
                                             })
                                             .OrderBy(li => li.Text), 
                                new { @class = "form-control", id = "mapLanguages" })
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">Apply</button>
        </div>
    </div>
</form>

Submodules/GMaps.Mvc/GMaps.Mvc.Examples/Views/Basic/Multimap.cshtml
@using GMaps.Mvc
@{
    ViewBag.Title = "Multiple Maps";
    Layout = "~/Views/Shared/_LayoutExamples.cshtml";
}


<div class="row">
    <div class="col-md-6" style="height: 300px">
        @(
            Html.GoogleMap()
                .Name("map")
         )
    </div>
    <div class="col-md-6" style="height: 300px">
        @(
            Html.GoogleMap()
                .Name("map1")
                .Center(c => c.Address("Madrid, Spain"))
        )
    </div>

</div>

Submodules/GMaps.Mvc/GMaps.Mvc.Examples/Views/Basic/UIControls.cshtml
@model GMaps.Mvc.Examples.Controllers.UIControlViewModel

@{
    ViewBag.Title = "UI Controls";
}

@(Html.GoogleMap()
                  .Name("map")
                  .Height(500)
                  .ScaleControlVisible(Model.ShowScaleControl)

                  .PanControlVisible(Model.ShowPanControl)
                  .PanControlPosition(Model.PanControlPosition)

                  .OverviewMapControlVisible(Model.ShowOverviewMapControl)
                  .OverviewMapControlOpened(Model.OverviewMapControlOpened)

                  .StreetViewControlVisible(Model.ShowStreetViewControl)
                  .StreetViewControlPosition(Model.StreetViewControlPosition)

                  .ZoomControlVisible(Model.ShowZoomControl)
                  .ZoomControlPosition(Model.ZoomControlPosition)
                  .ZoomControlStyle(Model.ZoomControlStyle)
                  .ScrollWheel(Model.ScrollWheel)

                  .MapTypeControlVisible(Model.ShowMapType)
                  .MapTypeId(Model.MapTypeControl)
                  .MapTypeControlStyle(Model.MapTypeControlStyle)
                  .MapTypeControlPosition(Model.MapTypeControlPosition)

)

<br />


<form class="form-horizontal" method="POST" role="form">
    <h4> Google Map Settings</h4>

    <div class="form-group">
        <div class="col-md-3">
            <div class="checkbox">
                <label>
                    @Html.CheckBox("ShowScaleControl", new { id = "mapShowScale" })
                    Show scale control
                </label>
            </div>
        </div>
        <div class="col-md-9">
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-3">
            <div class="checkbox">
                <label style="display:inline;">
                    @Html.CheckBox("ShowOverviewMapControl", new { id = "mapShowOverviewMapControl" })
                    Show overviewMap control
                </label>
            </div>
        </div>
        <div class="col-md-3">
            <div class="checkbox">
                <label style="display:inline;">
                    @Html.CheckBox("OverviewMapControlOpened", new { id = "mapOverviewMapControlOpened" })
                    Open overviewMap control
                </label>
            </div>
        </div>
        <div class="col-md-6"></div>
    </div>

    <div class="form-group">
        <div class="col-md-3">
            <div class="checkbox">
                <label style="display:inline;">
                    @Html.CheckBox("ShowPanControl", new { id = "mapShowPanControl" })
                    Show pan control
                </label>
            </div>
        </div>
        <div class="col-md-3">
            <label for="mapPanControlPosition" class="control-label" style="white-space: nowrap;">Position</label>
            @Html.DropDownList("PanControlPosition", new SelectList(typeof(ControlPosition).GetEnumDataSource(), "Key", "Value"), new { @class = "form-control", id = "mapPanControlPosition" })
        </div>
        <div class="col-md-6"></div>
    </div>

    <div class="form-group">
        <div class="col-md-3">
            <div class="checkbox">
                <label style="display:inline;">
                    @Html.CheckBox("ShowStreetViewControl", new { id = "mapShowStreetViewControl" })
                    Show street view control
                </label>
            </div>
        </div>
        <div class="col-md-3">
            <label for="mapStreetViewControlPosition" class="control-label" style="white-space: nowrap;">Position</label>
            @Html.DropDownList("StreetViewControlPosition", new SelectList(typeof(ControlPosition).GetEnumDataSource(), "Key", "Value"), new { @class = "form-control", id = "mapStreetViewControlPosition" })
        </div>
        <div class="col-md-6"></div>
    </div>

    <div class="form-group">
        <div class="col-md-3">
            <div class="checkbox">
                <label style="display:inline;">
                    @Html.CheckBox("ShowZoomControl", new { id = "mapShowZoomControl" })
                    Show zoom control
                </label>
            </div>
        </div>
        <div class="col-md-3">
            <label for="mapZoomControlPosition" class="control-label" style="white-space: nowrap;">Position</label>
            @Html.DropDownList("ZoomControlPosition", new SelectList(typeof(ControlPosition).GetEnumDataSource(), "Key", "Value"), new { @class = "form-control", id = "mapZoomControlPosition" })
        </div>
        <div class="col-md-3">
            <label for="mapZoomControlStyle" class="control-label" style="white-space: nowrap;">Style</label>
            @Html.DropDownList("ZoomControlStyle", new SelectList(typeof(ZoomControlStyle).GetEnumDataSource(), "Key", "Value"), new { @class = "form-control", id = "mapZoomControlStyle" })
        </div>
        <div class="col-md-3">
            <div class="checkbox">
                <label style="display:inline;">
                    @Html.CheckBox("ScrollWheel", new { id = "mapScrollWheel" })
                    Scroll Wheel
                </label>
            </div>
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-3">
            <div class="checkbox">
                <label style="display:inline;">
                    @Html.CheckBox("ShowMapType", new { id = "mapShowMapTypeControl" })
                    Show map type control
                </label>
            </div>
        </div>
        <div class="col-md-3">
            <label for="mapTypeControlPosition" class="control-label" style="white-space: nowrap;">Position</label>
            @Html.DropDownList("MapTypeControlPosition", new SelectList(typeof(ControlPosition).GetEnumDataSource(), "Key", "Value"), new { @class = "form-control", id = "mapTypeControlPosition" })
        </div>

        <div class="col-md-3">
            <label for="mapTypeStyle" class="control-label" style="white-space: nowrap;">Style</label>
            @Html.DropDownList("MapTypeControlStyle", new SelectList(typeof(MapTypeControlStyle).GetEnumDataSource(), "Key", "Value"), new { @class = "form-control", id = "mapTypeStyle" })
        </div>

        <div class="col-md-3">
            <label for="mapType" class="control-label" style="white-space: nowrap;">Type</label>
            @Html.DropDownList("MapTypeControl", new SelectList(typeof(MapType).GetEnumDataSource(), "Key", "Value"), new { @class = "form-control", id = "mapType" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-12">
            <button type="submit" class="btn btn-default">Apply</button>
        </div>
    </div>
</form>

Submodules/GMaps.Mvc/GMaps.Mvc.Examples/Views/Basic/Version.cshtml
@using GMaps.Mvc
@model string

@{
    ViewBag.Title = "GoogleMap Version";
}

<div style="height: 500px; border: solid 1px #cccccc">
    @(Html.GoogleMap()
          .Name("map")
          .Version(ViewData["version"] as string)
          .Height(500))
</div>

<br />

<form class="form-horizontal" role="form">
    <h4> Google Map Settings</h4>
    <div class="form-group">
        <label for="width" class="col-sm-2 control-label">Version</label>
        <div class="col-sm-4">
            @Html.DropDownList("version", 
                                new List<SelectListItem>
                                {
                                    new SelectListItem {Text = "Default", Value = ""},
                                    new SelectListItem {Text = "3.exp", Value = "3.exp"},
                                    new SelectListItem {Text = "3.20", Value = "3.20"},
                                    new SelectListItem {Text = "3.19", Value = "3.19"},
                                }, 
                                new { @class = "form-control", id = "mapHeight" }
                              )
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-offset-1 col-sm-10">
            <button type="submit" class="btn btn-default">Apply</button>
        </div>
    </div>
</form>

Submodules/GMaps.Mvc/GMaps.Mvc.Examples/Views/Basic/_GooglemapPartialView.cshtml
@using GMaps.Mvc

@{
    Html.GoogleMap()
        .Name("map")
        .Markers(marker => marker.Add()
            .Window(w => w.Add()
                .Content((o) => String.Format("Hello PartialView {0}", Model))))
        .Render();
}

@(Html.GoogleMap().LoadScripts())