GmWeb.Web.Profile/Models/Waitlist/CategoryData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using GmWeb.Logic.Enums;
using GmWeb.Logic.Utility.Extensions;
using GmWeb.Logic.Data.Models.Shared;

namespace GmWeb.Web.Profile.Models.Waitlist
{
    public class CategoryData : EditableFlowModelBase
    {
        public string VariableName { get; set; } = "New Variable";
        public override string EditorTitle => "Category Data";
        public override string EditorNameField => "VariableName";
        public int DataSourceID { get; set; }
        public int? CategoryID { get; set;  }
        public DynamicFieldValue ConfiguredValue { get; set; }
        public object ConvertedValue => this.ConfiguredValue.ConvertedValue;
        public string FormattedValue => this.ConfiguredValue.FormattedValue;
        public string LookupTableName { get; set; }
    }
}

GmWeb.Web.Profile/Models/Waitlist/Client.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace GmWeb.Web.Profile.Models.Waitlist
{
    public class Client
    {
        public int? ClientID { get; set; }
        public string FullName { get; set; }
        public int? Age { get; set; }
        public int? FamilySize { get; set; }
        public string Zip { get; set; }
        public string City { get; set; }
    }
}

GmWeb.Web.Profile/Models/Waitlist/ClientQuery.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using GmWeb.Logic.Enums;
using GmWeb.Logic.Data.Models;
using GmWeb.Web.Profile.Models.Shared;

namespace GmWeb.Web.Profile.Models.Waitlist
{
    public class ClientQuery : EditableFlowModelBase
    {
        public string VariableName { get; set; }
        public override string EditorNameField => "VariableName";
        public override string EditorTitle => "Client Query";
        public int DataSourceID { get; set; }
        public ClientResponse ClientResponse { get; set; }
        public string RequestText { get; set; }
        public string LookupTableName { get; set; }
    }
}

GmWeb.Web.Profile/Models/Waitlist/ClientResponse.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using GmWeb.Logic.Interfaces;
using GmWeb.Logic.Utility.Extensions;
using GmWeb.Logic.Data.Models.Shared;

namespace GmWeb.Web.Profile.Models.Waitlist
{
    public class ClientResponse : DynamicFieldValue, IViewModel
    {
        public string Guid { get; set; } = ModelExtensions.GenerateGuid();
    }
}

GmWeb.Web.Profile/Models/Waitlist/DataSource.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using GmWeb.Logic.Data.Context.Profile;
using GmWeb.Logic.Data.Models.Waitlists;
using AutoMapper;

namespace GmWeb.Web.Profile.Models.Waitlist
{
    public class DataSource : EditableFlowModelBase
    {
        public int DataSourceID { get; set; }
        public string Name => $"{this.EntityType}: {this.Field}";
        public string Table { get; set; } = string.Empty;
        public string Field { get; set; } = string.Empty;
        public EntityType EntityType { get; set; }

        public static IEnumerable<DataSource> Options(IMapper mapper)
        {
            using(var cache = new ProfileCache())
            {
                var dbSources = cache.DataSources.ToList();
                foreach (var source in dbSources)
                    yield return mapper.Map<DataSource>(source);
            }
        }
    }
}

GmWeb.Web.Profile/Models/Waitlist/EditableFlowModelBase.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using GmWeb.Web.Common.Models.Shared;

namespace GmWeb.Web.Profile.Models.Waitlist
{
    public abstract class EditableFlowModelBase : IEditableViewModel
    {
        public string Guid { get; set; } = GmWeb.Logic.Utility.Extensions.ModelExtensions.GenerateGuid();
        public virtual string EditorTitle => null;
        public virtual string EditorNameField => "Name";
        public virtual bool IsNameMultiline => false;
    }
}

GmWeb.Web.Profile/Models/Waitlist/FilterResultData.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GmWeb.Web.Profile.Models.Waitlist
{
    public class FilterResultData : EditableFlowModelBase
    {
        public int MatchCount { get; set; } = 0;
        public double? MatchPercentage { get; set; } = 0;
        public int TotalCount { get; set; } = 0;
        public List<Client> Clients { get; set; } = new List<Client>();
    }
}

GmWeb.Web.Profile/Models/Waitlist/Flow.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GmWeb.Web.Profile.Models.Waitlist
{
    public class Flow : EditableFlowModelBase
    {
        public int? WaitlistFlowID { get; set; }
        public string Name { get; set; } = "New Workflow";
        public override string EditorTitle => "Flow";
        public List<CategoryData> Data { get; set; } = new List<CategoryData>();
        public List<ResultSet> Results { get; set; } = new List<ResultSet>();
        public List<FlowStep> Steps { get; set; } = new List<FlowStep>();
    }
}

GmWeb.Web.Profile/Models/Waitlist/FlowLink.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GmWeb.Web.Profile.Models.Waitlist
{
    public class FlowLink : EditableFlowModelBase
    {
        public override string EditorTitle => "Flow Link";
        public bool IsLink { get; set; } = true;
        public Predicate Predicate { get; set; } = new Predicate();
        public string ConnectionGuid { get; set; }
        public string Name { get; set; }
        public string SourceStepGuid { get; set; }
        public string TargetStepGuid { get; set; }
    }
}

GmWeb.Web.Profile/Models/Waitlist/FlowStep.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using GmWeb.Logic.Data.Models.Waitlists;
using GmWeb.Logic.Enums;

namespace GmWeb.Web.Profile.Models.Waitlist
{
    public class FlowStep : EditableFlowModelBase
    {
        public override string EditorTitle => "Flow Step";
        public bool IsStep { get; set; } = true;
        public int? WaitlistFlowID { get; set; }
        public int? WaitlistFlowStepID { get; set; }
        public StepType StepType { get; set; }
        public bool IsInitial => this.StepType == StepType.Initial;
        public bool IsTerminal => this.StepType == StepType.Terminal;
        public string Name { get; set; }
        public string ShapeGuid { get; set; }
        public ShapeLayout Layout { get; set; } = new ShapeLayout();
        public List<ClientQuery> Queries { get; set; } = new List<ClientQuery>();
        public List<FlowLink> Links { get; set; } = new List<FlowLink>();
    }
}

GmWeb.Web.Profile/Models/Waitlist/Predicate.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace GmWeb.Web.Profile.Models.Waitlist
{
    public class Predicate : EditableFlowModelBase
    {
        public string Formula { get; set; }

        public Predicate() : this(string.Empty) { }
        public Predicate(string formula)
        {
            this.Formula = formula;
        }

        public static implicit operator string(Predicate p)
        {
            return p.Formula;
        }

        public static implicit operator Predicate(string s) => new Predicate(s);

        public override string ToString()
        {
            return this.Formula;
        }
    }
}

GmWeb.Web.Profile/Models/Waitlist/ResultSet.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using GmWeb.Web.Profile.Models.Shared;
using Newtonsoft.Json;

namespace GmWeb.Web.Profile.Models.Waitlist
{
    public class ResultSet : EditableFlowModelBase
    {
        public string Name { get; set; } = "New Result Set";
        public override string EditorTitle => "Result Set";
        public override bool IsNameMultiline => true;
        public List<Predicate> Predicates { get; set; } = new List<Predicate>();
        [JsonIgnore]
        public IEnumerable<string> Formulas => this.Predicates.Select(x => x.Formula);
        public FilterResultData Data { get; set; } = new FilterResultData();
    }
}

GmWeb.Web.Profile/Models/WaitlistViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using GmWeb.Web.Profile.Models.Waitlist;

namespace GmWeb.Web.Profile.Models
{
    public class WaitlistViewModel : GmWeb.Web.Common.Models.BasePageViewModel
    {
        public Flow Flow { get; set; }
    }
}

GmWeb.Web.Profile/Controllers/WaitlistController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using GmWeb.Web.Profile.Utility;
using GmWeb.Web.Profile.Models;
using GmWeb.Logic.Data.Context.Profile;
using DataModels = GmWeb.Logic.Data.Models.Waitlists;
using ViewModels = GmWeb.Web.Profile.Models.Waitlist;
using GmWeb.Logic.Utility.Extensions;
using GmWeb.Logic.Interfaces;
using Newtonsoft.Json;

namespace GmWeb.Web.Profile.Controllers
{
    public class WaitlistController : BaseClientServicesController<WaitlistViewModel>
    {
        // GET: Waitlist
        public ActionResult Index(int? FlowID, int? CategoryID = 264)
        {
            var model = this.CreateViewModel();
            using(var cache = new ProfileCache())
            {
                DataModels.Flow dbFlow;
                if (FlowID.HasValue)
                    dbFlow = cache.Flows.SingleOrDefault(x => x.FlowID == FlowID.Value);
                else dbFlow = cache.Flows.FirstOrDefault();
                dbFlow.PopulateReferences(cache.DataContext);
                var filter = new DataModels.ClientFilter(cache.DataContext);
                foreach (var dbData in dbFlow.Data)
                    dbData.ResolveLookup(cache.DataContext, CategoryID);
                foreach (var rs in dbFlow.Results)
                    rs.Data = filter.Evaluate(rs.Predicates, dbFlow);
                foreach (var step in dbFlow.Steps)
                    foreach (var q in step.Queries)
                        q.ResolveLookup(cache.DataContext, model.ClientID);
                model.Flow = this.Mapper.Map<ViewModels.Flow>(dbFlow);
            }
            if (model.Flow == null)
                throw new ArgumentException($"No waitlist flow configuration could be found with the requested ID: {FlowID}");
            return View(model);
        }

        // TODO: Convert this system of partials into react/angular controls
        [HttpPost]
        public ActionResult _FlowLinkEditor(ViewModels.FlowLink Model)
        {
            ViewBag.TitleSize = 36;
            ViewBag.IsCollapsible = true;
            return this.EditorContainer(Model);
        }

        [HttpPost]
        public ActionResult _FlowStepEditor(ViewModels.FlowStep Model)
        {
            ViewBag.TitleSize = 36;
            ViewBag.IsCollapsible = true;
            return this.EditorContainer(Model);
        }

        [HttpPost]
        public ActionResult _FlowEditor(ViewModels.Flow Model)
        {
            ViewBag.TitleSize = 36;
            ViewBag.IsCollapsible = true;
            return this.EditorContainer(Model);
        }

        [HttpPost]
        public ActionResult _FlowStepViewer(ViewModels.FlowStep Model)
        {
            return this.DisplayContainer(Model);
        }

        [HttpPost]
        public ActionResult SaveFlow(ViewModels.Flow Model)
        {
            using(var context = new ProfileCache())
            {
                var dbFlow = this.Mapper.Map<DataModels.Flow>(Model);
                context.Flows.Update(dbFlow);
                foreach(var step in dbFlow.Steps)
                {
                    var dbStep = this.Mapper.Map<DataModels.FlowStep>(step);
                    if (context.FlowSteps.Any(x => x.FlowStepID == step.FlowStepID))
                        context.FlowSteps.Update(dbStep);
                    else
                        context.FlowSteps.Add(dbStep);
                }
                context.Save();
            }
            return this.JsonSuccess();
        }
    }
}

GmWeb.Web.Profile/Views/Waitlist/Scripts/_FlowEditorScripts.cshtml
@using GmWeb.Web.Profile.Models.Waitlist
@using GmWeb.Web.Profile.Models
@model  WaitlistViewModel

@* Flow Initialization *@
<script>
    var FlowContext = {
        Initializers: {},
        ModelMap: {},
        ShapeMap: {},
        ConnectionMap: {},
        Flow: null,
        save: function () {
            var url = '@Url.Action("SaveFlow","Waitlist")';
            var payload = this.Flow.toJSON();
            $.ajax({
                type: 'POST',
                url: url,
                data: { Model: payload },
                success: function (data) {
                    alert('Success!');
                },
                error: function (e) {
                    alert('Error saving flow.');
                    console.error('err:', e);
                }
            });
        },
        create: function (options) {
            var self = this;
            self.instantiate(options, function (instance, editor) {
                instance = options.Instance = kendo.observable(instance);
                instance.Editor = editor;
                self.ModelMap[instance.Guid] = instance;
                var initializer;
                if (options.TypeName in self.Initializers) {
                    initializer = self.Initializers[options.TypeName];
                } else {
                    initializer = self.Initializers.Default;
                }
                initializer.call(null, options);
                InspiniaInitializer(); // TODO: Don't re-initialize the same elements
                bindRecursively(instance);
            });
        },
        instantiate: function (options, callback) {
            var url = '@Url.Action("CreateInstanceWithEditor","Api")';
            var data = {
                TypeName: options.TypeName,
                IsCollectionItem: options.Collection != null,
                CollectionName: options.CollectionName,
                StartCollapsed: true
            };
            console.log('called _FlowEditorScripts.instantiate; request url:', url);
            $.ajax({
                type: 'POST',
                url: url,
                data: data,
                success: function (data) {
                    if (callback != null)
                        callback(data.Instance, data.Editor);
                },
                error: function (e) {
                    console.error('err:', e);
                }
            });
        },
        initialize: function () {
            console.log('called _FlowEditorScripts.initialize');
            var self = this;
            self.refreshModel();
            self.ModelMap = self.buildMap();
            self.Initializers.FlowLink = function (options) {
                var
                    link = options.Instance,
                    source = options.SourceShape,
                    target = options.TargetShape
                ;
                link.SourceStepGuid = source.Guid;
                link.TargetStepGuid = target.Guid;
                link.Name = 'New Link';
                source.Links.push(link);
            };
            self.Initializers.FlowStep = function (options) {
                var step = options.Instance;
                step.Name = 'New Step';
                step.WaitlistFlowID = self.Flow.WaitlistFlowID;
                self.Flow.Steps.push(step);
            };
            self.Initializers.Default = function (options) {
                options.Collection.push(options.Instance);
            };
        },
        buildMap: function (node) {
            if (node == null) {
                node = this.Flow;
                console.log(`called _FlowEditorScripts:buildMap on parent flow[id=${this.Flow.Guid}`)
            }
            var map = {};
            if (node.Guid != null) {
                map[node.Guid] = node;
            }
            var keys = Object.keys(node);
            $.each(keys, (idx, key) => {
                var child = node[key];
                if ($.isPlainObject(child) || $.isArray(child) || child instanceof kendo.Observable) {
                    var childMap = this.buildMap(child);
                    $.extend(map, childMap);
                }
            });
            return map;
        },
        refreshModel: function () {
            var model = @(Html.ConvertInstanceToJs(Model.Flow));
            var observable = kendo.observable(model);
            this.Flow = observable;
        }
    };
</script>

@* Collection Editing *@
<script>
    $.extend(FlowContext, {
        addCollectionItem: function (parentGuid, collectionPropertyName, collectionTypeName) {
            var parent = this.ModelMap[parentGuid];
            var parentCollection = parent[collectionPropertyName];
            this.create({ TypeName: collectionTypeName, Collection: parentCollection, CollectionName: collectionPropertyName, Parent: parent });
        },
        removeCollectionItem: function (parentGuid, collectionPropertyName, itemGuid) {
            var parent = this.ModelMap[parentGuid];
            var parentCollection = parent[collectionPropertyName];
            var child = this.ModelMap[itemGuid];
            parentCollection.remove(child);
        },
        clearCollection: function (parentGuid, collectionPropertyName) {
            var parent = this.ModelMap[parentGuid];
            var parentCollection = parent[collectionPropertyName];
            parentCollection.clear();
        },
        bindToCollection: function (parentGuid, collectionPropertyName, handler) {
            var parent = this.ModelMap[parentGuid];
            var parentCollection = parent[collectionPropertyName];
            parentCollection.bind('change', handler);
        }
    });
</script>
<script>
    $(function () {
        FlowContext.initialize();
    });
</script>